/********************************************************************************
** Form generated from reading UI file 'manager.ui'
**
** Created by: Qt User Interface Compiler version 6.4.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MANAGER_H
#define UI_MANAGER_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Manager
{
public:
    QWidget *centralwidget;
    QStackedWidget *ManagerMain;
    QWidget *page;
    QLabel *ManagerImg;
    QGroupBox *groupBox_2;
    QPushButton *managerCreateEmployeeButton;
    QPushButton *managerUpdateEmployeeButton;
    QPushButton *managerDeleteEmployeeButton;
    QLabel *label;
    QGroupBox *groupBox_5;
    QPushButton *managerCreateTechnicianButton;
    QGroupBox *groupBox_4;
    QPushButton *managerEmployeeReportButton;
    QGroupBox *groupBox_3;
    QPushButton *managerAddVehicleButton;
    QPushButton *managerEditVehicleButton;
    QPushButton *managerDeleteVehicleButton;
    QGroupBox *groupBox;
    QPushButton *managerCreateCustomersButton;
    QPushButton *managerUpdateCustomersButton;
    QPushButton *managerDeleteCustomersButton;
    QPushButton *managerUpdateTechnicianButton;
    QPushButton *managerDeleteTechnicianButton;
    QGroupBox *groupBox_6;
    QPushButton *managerViewContractButton;
    QPushButton *managerApproveContractButton;
    QPushButton *managerDeleteContractButton;
    QGroupBox *groupBox_7;
    QPushButton *managerRequestApprovalButton;
    QPushButton *managerLogoutButton;
    QWidget *page_2;
    QLabel *label_2;
    QPushButton *Back_1;
    QWidget *page_3;
    QLabel *label_3;
    QPushButton *Back_2;
    QWidget *page_4;
    QLabel *label_4;
    QPushButton *Back_3;
    QWidget *page_5;
    QLabel *label_5;
    QPushButton *Back_4;
    QWidget *page_6;
    QLabel *label_6;
    QPushButton *Back_5;
    QWidget *page_7;
    QLabel *label_7;
    QPushButton *Back_6;
    QWidget *page_8;
    QLabel *label_10;
    QPushButton *Back_7;
    QWidget *page_9;
    QLabel *label_11;
    QPushButton *Back_8;
    QWidget *page_10;
    QLabel *label_12;
    QPushButton *Back_9;
    QWidget *page_11;
    QLabel *label_13;
    QPushButton *Back_10;
    QWidget *page_12;
    QLabel *label_14;
    QPushButton *Back_11;
    QWidget *page_13;
    QLabel *label_15;
    QPushButton *Back_12;
    QWidget *page_14;
    QLabel *label_27;
    QPushButton *Back_25;
    QWidget *page_29;
    QLabel *label_28;
    QPushButton *Back_;
    QWidget *page_30;
    QPushButton *DeleteContracts_Back;
    QLabel *label_29;
    QWidget *page_31;
    QGroupBox *groupBox_15;
    QPushButton *managerEmployeeReportButton_3;
    QPushButton *managerCustomerReportButton_3;
    QPushButton *managerVehicleReportButton_3;
    QTableView *tableView;
    QPushButton *Reports_Back_3;
    QWidget *page_32;
    QPushButton *RepairRequestApproved_Back;
    QLabel *label_30;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *Manager)
    {
        if (Manager->objectName().isEmpty())
            Manager->setObjectName("Manager");
        Manager->resize(1529, 786);
        centralwidget = new QWidget(Manager);
        centralwidget->setObjectName("centralwidget");
        ManagerMain = new QStackedWidget(centralwidget);
        ManagerMain->setObjectName("ManagerMain");
        ManagerMain->setGeometry(QRect(10, 0, 1511, 751));
        page = new QWidget();
        page->setObjectName("page");
        ManagerImg = new QLabel(page);
        ManagerImg->setObjectName("ManagerImg");
        ManagerImg->setGeometry(QRect(990, 40, 621, 851));
        ManagerImg->setScaledContents(true);
        groupBox_2 = new QGroupBox(page);
        groupBox_2->setObjectName("groupBox_2");
        groupBox_2->setGeometry(QRect(200, 260, 171, 151));
        QFont font;
        font.setBold(true);
        groupBox_2->setFont(font);
        managerCreateEmployeeButton = new QPushButton(groupBox_2);
        managerCreateEmployeeButton->setObjectName("managerCreateEmployeeButton");
        managerCreateEmployeeButton->setGeometry(QRect(10, 30, 83, 29));
        managerCreateEmployeeButton->setFont(font);
        managerUpdateEmployeeButton = new QPushButton(groupBox_2);
        managerUpdateEmployeeButton->setObjectName("managerUpdateEmployeeButton");
        managerUpdateEmployeeButton->setGeometry(QRect(10, 70, 83, 29));
        managerUpdateEmployeeButton->setFont(font);
        managerDeleteEmployeeButton = new QPushButton(groupBox_2);
        managerDeleteEmployeeButton->setObjectName("managerDeleteEmployeeButton");
        managerDeleteEmployeeButton->setGeometry(QRect(10, 110, 83, 29));
        managerDeleteEmployeeButton->setFont(font);
        label = new QLabel(page);
        label->setObjectName("label");
        label->setGeometry(QRect(140, 10, 231, 41));
        QFont font1;
        font1.setPointSize(10);
        font1.setBold(true);
        label->setFont(font1);
        groupBox_5 = new QGroupBox(page);
        groupBox_5->setObjectName("groupBox_5");
        groupBox_5->setGeometry(QRect(200, 440, 171, 151));
        groupBox_5->setFont(font);
        managerCreateTechnicianButton = new QPushButton(groupBox_5);
        managerCreateTechnicianButton->setObjectName("managerCreateTechnicianButton");
        managerCreateTechnicianButton->setGeometry(QRect(10, 30, 83, 29));
        managerCreateTechnicianButton->setFont(font);
        groupBox_4 = new QGroupBox(page);
        groupBox_4->setObjectName("groupBox_4");
        groupBox_4->setGeometry(QRect(510, 420, 181, 71));
        groupBox_4->setFont(font);
        managerEmployeeReportButton = new QPushButton(groupBox_4);
        managerEmployeeReportButton->setObjectName("managerEmployeeReportButton");
        managerEmployeeReportButton->setGeometry(QRect(10, 30, 131, 29));
        managerEmployeeReportButton->setFont(font);
        groupBox_3 = new QGroupBox(page);
        groupBox_3->setObjectName("groupBox_3");
        groupBox_3->setGeometry(QRect(510, 60, 171, 171));
        groupBox_3->setFont(font);
        managerAddVehicleButton = new QPushButton(groupBox_3);
        managerAddVehicleButton->setObjectName("managerAddVehicleButton");
        managerAddVehicleButton->setGeometry(QRect(10, 50, 83, 29));
        managerAddVehicleButton->setFont(font);
        managerEditVehicleButton = new QPushButton(groupBox_3);
        managerEditVehicleButton->setObjectName("managerEditVehicleButton");
        managerEditVehicleButton->setGeometry(QRect(10, 90, 83, 29));
        managerEditVehicleButton->setFont(font);
        managerDeleteVehicleButton = new QPushButton(groupBox_3);
        managerDeleteVehicleButton->setObjectName("managerDeleteVehicleButton");
        managerDeleteVehicleButton->setGeometry(QRect(10, 130, 83, 29));
        managerDeleteVehicleButton->setFont(font);
        groupBox = new QGroupBox(page);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(200, 70, 171, 161));
        groupBox->setFont(font);
        managerCreateCustomersButton = new QPushButton(groupBox);
        managerCreateCustomersButton->setObjectName("managerCreateCustomersButton");
        managerCreateCustomersButton->setGeometry(QRect(10, 40, 83, 29));
        managerCreateCustomersButton->setFont(font);
        managerUpdateCustomersButton = new QPushButton(groupBox);
        managerUpdateCustomersButton->setObjectName("managerUpdateCustomersButton");
        managerUpdateCustomersButton->setGeometry(QRect(10, 80, 83, 29));
        managerUpdateCustomersButton->setFont(font);
        managerDeleteCustomersButton = new QPushButton(groupBox);
        managerDeleteCustomersButton->setObjectName("managerDeleteCustomersButton");
        managerDeleteCustomersButton->setGeometry(QRect(10, 120, 83, 29));
        managerDeleteCustomersButton->setFont(font);
        managerUpdateTechnicianButton = new QPushButton(page);
        managerUpdateTechnicianButton->setObjectName("managerUpdateTechnicianButton");
        managerUpdateTechnicianButton->setGeometry(QRect(210, 510, 83, 29));
        managerUpdateTechnicianButton->setFont(font);
        managerDeleteTechnicianButton = new QPushButton(page);
        managerDeleteTechnicianButton->setObjectName("managerDeleteTechnicianButton");
        managerDeleteTechnicianButton->setGeometry(QRect(210, 550, 83, 29));
        managerDeleteTechnicianButton->setFont(font);
        groupBox_6 = new QGroupBox(page);
        groupBox_6->setObjectName("groupBox_6");
        groupBox_6->setGeometry(QRect(510, 260, 181, 151));
        groupBox_6->setFont(font);
        managerViewContractButton = new QPushButton(groupBox_6);
        managerViewContractButton->setObjectName("managerViewContractButton");
        managerViewContractButton->setGeometry(QRect(10, 30, 131, 29));
        managerViewContractButton->setFont(font);
        managerApproveContractButton = new QPushButton(groupBox_6);
        managerApproveContractButton->setObjectName("managerApproveContractButton");
        managerApproveContractButton->setGeometry(QRect(10, 70, 131, 29));
        managerApproveContractButton->setFont(font);
        managerDeleteContractButton = new QPushButton(groupBox_6);
        managerDeleteContractButton->setObjectName("managerDeleteContractButton");
        managerDeleteContractButton->setGeometry(QRect(10, 110, 131, 29));
        managerDeleteContractButton->setFont(font);
        groupBox_7 = new QGroupBox(page);
        groupBox_7->setObjectName("groupBox_7");
        groupBox_7->setGeometry(QRect(510, 500, 191, 81));
        groupBox_7->setFont(font);
        managerRequestApprovalButton = new QPushButton(groupBox_7);
        managerRequestApprovalButton->setObjectName("managerRequestApprovalButton");
        managerRequestApprovalButton->setGeometry(QRect(10, 30, 151, 41));
        managerRequestApprovalButton->setFont(font);
        managerLogoutButton = new QPushButton(page);
        managerLogoutButton->setObjectName("managerLogoutButton");
        managerLogoutButton->setGeometry(QRect(1240, 0, 83, 29));
        ManagerMain->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        label_2 = new QLabel(page_2);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(50, 0, 121, 21));
        label_2->setFont(font);
        Back_1 = new QPushButton(page_2);
        Back_1->setObjectName("Back_1");
        Back_1->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        label_3 = new QLabel(page_3);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(10, 0, 131, 21));
        label_3->setFont(font);
        Back_2 = new QPushButton(page_3);
        Back_2->setObjectName("Back_2");
        Back_2->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        label_4 = new QLabel(page_4);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(10, 0, 121, 21));
        label_4->setFont(font);
        Back_3 = new QPushButton(page_4);
        Back_3->setObjectName("Back_3");
        Back_3->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName("page_5");
        label_5 = new QLabel(page_5);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(10, 0, 171, 16));
        label_5->setFont(font);
        Back_4 = new QPushButton(page_5);
        Back_4->setObjectName("Back_4");
        Back_4->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName("page_6");
        label_6 = new QLabel(page_6);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(0, 0, 171, 21));
        label_6->setFont(font);
        Back_5 = new QPushButton(page_6);
        Back_5->setObjectName("Back_5");
        Back_5->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName("page_7");
        label_7 = new QLabel(page_7);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(0, 0, 171, 21));
        label_7->setFont(font);
        Back_6 = new QPushButton(page_7);
        Back_6->setObjectName("Back_6");
        Back_6->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName("page_8");
        label_10 = new QLabel(page_8);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(10, 0, 171, 21));
        label_10->setFont(font);
        Back_7 = new QPushButton(page_8);
        Back_7->setObjectName("Back_7");
        Back_7->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_8);
        page_9 = new QWidget();
        page_9->setObjectName("page_9");
        label_11 = new QLabel(page_9);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(0, 0, 171, 21));
        label_11->setFont(font);
        Back_8 = new QPushButton(page_9);
        Back_8->setObjectName("Back_8");
        Back_8->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_9);
        page_10 = new QWidget();
        page_10->setObjectName("page_10");
        label_12 = new QLabel(page_10);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(0, 0, 191, 21));
        label_12->setFont(font);
        Back_9 = new QPushButton(page_10);
        Back_9->setObjectName("Back_9");
        Back_9->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_10);
        page_11 = new QWidget();
        page_11->setObjectName("page_11");
        label_13 = new QLabel(page_11);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(10, 0, 221, 21));
        label_13->setFont(font);
        Back_10 = new QPushButton(page_11);
        Back_10->setObjectName("Back_10");
        Back_10->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_11);
        page_12 = new QWidget();
        page_12->setObjectName("page_12");
        label_14 = new QLabel(page_12);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(10, 0, 221, 21));
        label_14->setFont(font);
        Back_11 = new QPushButton(page_12);
        Back_11->setObjectName("Back_11");
        Back_11->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_12);
        page_13 = new QWidget();
        page_13->setObjectName("page_13");
        label_15 = new QLabel(page_13);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(0, 0, 201, 41));
        label_15->setFont(font);
        Back_12 = new QPushButton(page_13);
        Back_12->setObjectName("Back_12");
        Back_12->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_13);
        page_14 = new QWidget();
        page_14->setObjectName("page_14");
        label_27 = new QLabel(page_14);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(0, 0, 201, 41));
        label_27->setFont(font);
        Back_25 = new QPushButton(page_14);
        Back_25->setObjectName("Back_25");
        Back_25->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_14);
        page_29 = new QWidget();
        page_29->setObjectName("page_29");
        label_28 = new QLabel(page_29);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(0, 0, 201, 41));
        label_28->setFont(font);
        Back_ = new QPushButton(page_29);
        Back_->setObjectName("Back_");
        Back_->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_29);
        page_30 = new QWidget();
        page_30->setObjectName("page_30");
        DeleteContracts_Back = new QPushButton(page_30);
        DeleteContracts_Back->setObjectName("DeleteContracts_Back");
        DeleteContracts_Back->setGeometry(QRect(1400, 0, 83, 29));
        label_29 = new QLabel(page_30);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(0, 0, 201, 41));
        label_29->setFont(font);
        ManagerMain->addWidget(page_30);
        page_31 = new QWidget();
        page_31->setObjectName("page_31");
        groupBox_15 = new QGroupBox(page_31);
        groupBox_15->setObjectName("groupBox_15");
        groupBox_15->setGeometry(QRect(0, 0, 181, 151));
        groupBox_15->setFont(font);
        managerEmployeeReportButton_3 = new QPushButton(groupBox_15);
        managerEmployeeReportButton_3->setObjectName("managerEmployeeReportButton_3");
        managerEmployeeReportButton_3->setGeometry(QRect(10, 30, 131, 29));
        managerEmployeeReportButton_3->setFont(font);
        managerCustomerReportButton_3 = new QPushButton(groupBox_15);
        managerCustomerReportButton_3->setObjectName("managerCustomerReportButton_3");
        managerCustomerReportButton_3->setGeometry(QRect(10, 70, 131, 29));
        managerCustomerReportButton_3->setFont(font);
        managerVehicleReportButton_3 = new QPushButton(groupBox_15);
        managerVehicleReportButton_3->setObjectName("managerVehicleReportButton_3");
        managerVehicleReportButton_3->setGeometry(QRect(10, 100, 131, 29));
        managerVehicleReportButton_3->setFont(font);
        tableView = new QTableView(page_31);
        tableView->setObjectName("tableView");
        tableView->setGeometry(QRect(190, 80, 1151, 561));
        Reports_Back_3 = new QPushButton(page_31);
        Reports_Back_3->setObjectName("Reports_Back_3");
        Reports_Back_3->setGeometry(QRect(1400, 0, 83, 29));
        ManagerMain->addWidget(page_31);
        page_32 = new QWidget();
        page_32->setObjectName("page_32");
        RepairRequestApproved_Back = new QPushButton(page_32);
        RepairRequestApproved_Back->setObjectName("RepairRequestApproved_Back");
        RepairRequestApproved_Back->setGeometry(QRect(1400, 0, 83, 29));
        label_30 = new QLabel(page_32);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(0, 0, 201, 41));
        label_30->setFont(font);
        ManagerMain->addWidget(page_32);
        Manager->setCentralWidget(centralwidget);
        menubar = new QMenuBar(Manager);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 1529, 25));
        Manager->setMenuBar(menubar);
        statusbar = new QStatusBar(Manager);
        statusbar->setObjectName("statusbar");
        Manager->setStatusBar(statusbar);

        retranslateUi(Manager);

        ManagerMain->setCurrentIndex(17);


        QMetaObject::connectSlotsByName(Manager);
    } // setupUi

    void retranslateUi(QMainWindow *Manager)
    {
        Manager->setWindowTitle(QCoreApplication::translate("Manager", "MainWindow", nullptr));
        ManagerImg->setText(QCoreApplication::translate("Manager", "IMG", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("Manager", "Employees", nullptr));
        managerCreateEmployeeButton->setText(QCoreApplication::translate("Manager", "Create", nullptr));
        managerUpdateEmployeeButton->setText(QCoreApplication::translate("Manager", "Update", nullptr));
        managerDeleteEmployeeButton->setText(QCoreApplication::translate("Manager", "Delete", nullptr));
        label->setText(QCoreApplication::translate("Manager", "Logged in as Manager User", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("Manager", "Technicians", nullptr));
        managerCreateTechnicianButton->setText(QCoreApplication::translate("Manager", "Create", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("Manager", "Reports", nullptr));
        managerEmployeeReportButton->setText(QCoreApplication::translate("Manager", "Go", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("Manager", "Vehicles", nullptr));
        managerAddVehicleButton->setText(QCoreApplication::translate("Manager", "Add", nullptr));
        managerEditVehicleButton->setText(QCoreApplication::translate("Manager", "Edit", nullptr));
        managerDeleteVehicleButton->setText(QCoreApplication::translate("Manager", "Delete", nullptr));
        groupBox->setTitle(QCoreApplication::translate("Manager", "Customers", nullptr));
        managerCreateCustomersButton->setText(QCoreApplication::translate("Manager", "Create", nullptr));
        managerUpdateCustomersButton->setText(QCoreApplication::translate("Manager", "Update", nullptr));
        managerDeleteCustomersButton->setText(QCoreApplication::translate("Manager", "Delete", nullptr));
        managerUpdateTechnicianButton->setText(QCoreApplication::translate("Manager", "Update", nullptr));
        managerDeleteTechnicianButton->setText(QCoreApplication::translate("Manager", "Delete", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("Manager", "Contracts", nullptr));
        managerViewContractButton->setText(QCoreApplication::translate("Manager", "View Contracts", nullptr));
        managerApproveContractButton->setText(QCoreApplication::translate("Manager", "Approve Contracts", nullptr));
        managerDeleteContractButton->setText(QCoreApplication::translate("Manager", "Delete Contracts", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("Manager", " Repair Request Approval", nullptr));
        managerRequestApprovalButton->setText(QCoreApplication::translate("Manager", "Request Approved", nullptr));
        managerLogoutButton->setText(QCoreApplication::translate("Manager", "Logout", nullptr));
        label_2->setText(QCoreApplication::translate("Manager", "Create Customer", nullptr));
        Back_1->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_3->setText(QCoreApplication::translate("Manager", "Update Customer", nullptr));
        Back_2->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_4->setText(QCoreApplication::translate("Manager", "Delete Customer", nullptr));
        Back_3->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_5->setText(QCoreApplication::translate("Manager", "Create Employees", nullptr));
        Back_4->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_6->setText(QCoreApplication::translate("Manager", "Update  Employees", nullptr));
        Back_5->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_7->setText(QCoreApplication::translate("Manager", "Delete  Employees", nullptr));
        Back_6->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_10->setText(QCoreApplication::translate("Manager", "Create Technicians", nullptr));
        Back_7->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_11->setText(QCoreApplication::translate("Manager", "Update Technicians", nullptr));
        Back_8->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_12->setText(QCoreApplication::translate("Manager", "Delete Technicians", nullptr));
        Back_9->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_13->setText(QCoreApplication::translate("Manager", "Add Vehicles", nullptr));
        Back_10->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_14->setText(QCoreApplication::translate("Manager", "Edit Vehicles", nullptr));
        Back_11->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_15->setText(QCoreApplication::translate("Manager", "Delete Vehicles", nullptr));
        Back_12->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_27->setText(QCoreApplication::translate("Manager", "View Contracts", nullptr));
        Back_25->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_28->setText(QCoreApplication::translate("Manager", "Approve Contracts", nullptr));
        Back_->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        DeleteContracts_Back->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_29->setText(QCoreApplication::translate("Manager", "Delete Contracts", nullptr));
        groupBox_15->setTitle(QCoreApplication::translate("Manager", "Reports", nullptr));
        managerEmployeeReportButton_3->setText(QCoreApplication::translate("Manager", "Employee Reports", nullptr));
        managerCustomerReportButton_3->setText(QCoreApplication::translate("Manager", "Customer Reports", nullptr));
        managerVehicleReportButton_3->setText(QCoreApplication::translate("Manager", "Vehicle Reports", nullptr));
        Reports_Back_3->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        RepairRequestApproved_Back->setText(QCoreApplication::translate("Manager", "Back", nullptr));
        label_30->setText(QCoreApplication::translate("Manager", "Repair Request Approved", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Manager: public Ui_Manager {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MANAGER_H
